name: signtracker
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.5+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  meta: ^1.1.8
  equatable: ^0.2.0
  google_maps_flutter: ^1.0.6 
  location: 2.3.5
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  built_collection: ^4.3.2
  built_value: ^7.1.0
  intl: ^0.16.1
  flutter_secure_storage: ^3.3.1+1
  image_picker: ^0.6.7
  progress_dialog: ^1.2.3
  flutter_slidable: ^0.5.4
  latlong: ^0.6.1
  flutter_launcher_icons: ^0.7.4
  jiffy: ^2.2.0
  keyboard_actions: ^3.2.1
  smart_select: ^4.3.2
  flutter_svg: ^0.19.0
  rflutter_alert: ^1.0.3
  flushbar: 1.10.2
  rounded_loading_button: ^1.0.4
  google_fonts: ^1.0.0
  onesignal_flutter: ^2.6.1
  flutter_device_type: ^0.2.0
  photo_view: ^0.9.2
  url_launcher: ^5.4.5
  grouped_list: ^2.3.0
  path_provider: ^1.6.7
  http: ^0.12.0+4
  badges: ^1.1.1
  uuid: ^2.0.4
  dropdown_formfield: ^0.1.2
  cached_network_image: ^2.1.0+1
  shared_preferences: ^0.5.7
  flutter_ringtone_player: ^3.0.0
  uni_links: ^0.4.0
  firebase_dynamic_links: ^0.5.0+11
  file_picker: ^1.9.0+1
  filesize: ^1.0.4
  responsive_framework: ^0.0.7
  cupertino_icons: ^1.0.0
  package_info_plus: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: any
  build_runner: any  

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/drawables/
    - assets/countries_regions.json
    - google_fonts/

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true